// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmQRL_0ijBDpnsM6gbKWjX_jSwvxDIFE',
    appId: '1:798761542219:web:4dfa5e9c5d5d14e5f523ce',
    messagingSenderId: '798761542219',
    projectId: 'registration-5eb86',
    authDomain: 'registration-5eb86.firebaseapp.com',
    storageBucket: 'registration-5eb86.firebasestorage.app',
    measurementId: 'G-70CBHYLLWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOcA1cj_vvnZ0s7h5E9mvUYQ4Jrcug1wU',
    appId: '1:798761542219:android:8b6ec4f8099be9c7f523ce',
    messagingSenderId: '798761542219',
    projectId: 'registration-5eb86',
    storageBucket: 'registration-5eb86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjS-D7kBmfCItS0OmLzY-d4tI91YuIOqQ',
    appId: '1:798761542219:ios:61727eac43b22d5cf523ce',
    messagingSenderId: '798761542219',
    projectId: 'registration-5eb86',
    storageBucket: 'registration-5eb86.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjS-D7kBmfCItS0OmLzY-d4tI91YuIOqQ',
    appId: '1:798761542219:ios:61727eac43b22d5cf523ce',
    messagingSenderId: '798761542219',
    projectId: 'registration-5eb86',
    storageBucket: 'registration-5eb86.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwmQRL_0ijBDpnsM6gbKWjX_jSwvxDIFE',
    appId: '1:798761542219:web:a355a3067076e38ef523ce',
    messagingSenderId: '798761542219',
    projectId: 'registration-5eb86',
    authDomain: 'registration-5eb86.firebaseapp.com',
    storageBucket: 'registration-5eb86.firebasestorage.app',
    measurementId: 'G-6CW786PMBX',
  );
}
